# Generated by Django 5.2.15 on 2026-06-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completion",
            field=models.BooleanField(default=False),
        ),
    ]
